-- MySQL Script generated by MySQL Workbench
-- Wed Mar 30 23:05:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema social
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema social
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `social` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema review
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema review
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `review` ;
USE `social` ;

-- -----------------------------------------------------
-- Table `social`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social`.`user` (
  `fName` VARCHAR(45) NOT NULL,
  `lName` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `phNumber` VARCHAR(10) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `gradelvl` VARCHAR(45) NOT NULL,
  `userid` INT NOT NULL AUTO_INCREMENT,
  `collegeATD` VARCHAR(75) NULL,
  PRIMARY KEY (`userid`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social`.`friend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social`.`friend` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social`.`follower`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social`.`follower` (
  `userid` INT NOT NULL,
  `followerid` INT NOT NULL,
  PRIMARY KEY (`userid`, `followerid`),
  CONSTRAINT `userid`
    FOREIGN KEY (`userid` , `followerid`)
    REFERENCES `social`.`user` (`userid` , `userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `followingid`
    FOREIGN KEY (`userid` , `followerid`)
    REFERENCES `social`.`user` (`userid` , `userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social`.`message` (
  `messageid` INT NOT NULL,
  `useridfrom` INT NOT NULL,
  `useridto` INT NOT NULL,
  `message` VARCHAR(255) NOT NULL,
  `date` DATETIME NULL,
  INDEX `useridfrom_idx` (`useridfrom` ASC, `useridto` ASC) VISIBLE,
  CONSTRAINT `useridfrom`
    FOREIGN KEY (`useridfrom` , `useridto`)
    REFERENCES `social`.`user` (`userid` , `userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social`.`post` (
  `idpost` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NOT NULL,
  `caption` VARCHAR(255) NULL,
  `dateCreate` DATETIME NULL,
  PRIMARY KEY (`idpost`),
  INDEX `userid_idx` (`userid` ASC) VISIBLE,
  CONSTRAINT `userid`
    FOREIGN KEY (`userid`)
    REFERENCES `social`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social`.`comment` (
  `idcomment` INT NULL AUTO_INCREMENT,
  `postid` INT NOT NULL,
  `userid` INT NOT NULL,
  `comment` VARCHAR(255) NOT NULL,
  `dateCreate` DATETIME NOT NULL,
  PRIMARY KEY (`idcomment`),
  INDEX `postid_idx` (`userid` ASC, `postid` ASC) VISIBLE,
  INDEX `userid_idx` (`postid` ASC) VISIBLE,
  CONSTRAINT `postid`
    FOREIGN KEY (`userid` , `postid`)
    REFERENCES `social`.`user` (`userid` , `userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userid`
    FOREIGN KEY (`postid`)
    REFERENCES `social`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `review` ;

-- -----------------------------------------------------
-- Table `review`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `review`.`review` (
  `idreview` INT NULL AUTO_INCREMENT,
  `name` VARCHAR(75) NOT NULL,
  `review` VARCHAR(255) NOT NULL,
  `rating` TINYINT(1) NOT NULL,
  `reviewdate` DATETIME NOT NULL,
  PRIMARY KEY (`idreview`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
